Repository garyvh2/shozas, pull requests merged in 2019-04, with the labels that each got.

#53 Feature/gitgud search endpoint
  src/main/java/com/gitgud/api/objects/ApiRealState.java
  src/main/java/com/gitgud/api/objects/ApiSearchResults.java
  src/main/java/com/gitgud/domain/RealState.java
  src/main/java/com/gitgud/repository/UserRepository.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/UserService.java
Labels: bug, feature

#54 Fixing issue when creating real state
  src/main/java/com/gitgud/service/RealStateService.java
Labels: feature

#57 Return all kind of elements
  src/main/java/com/gitgud/api/objects/ApiRealState.java
  src/main/java/com/gitgud/config/SecurityConfiguration.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/util/ResultType.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
Labels: feature

#58 Edit real state
  src/main/java/com/gitgud/service/RealStateService.java
Labels: bug

#64 Feature/gitgud recommendations
  package-lock.json
  pom.xml
  src/main/java/com/gitgud/api/objects/ApiDetailView.java
  src/main/java/com/gitgud/config/SecurityConfiguration.java
  src/main/java/com/gitgud/domain/RealState.java
  src/main/java/com/gitgud/domain/User.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/UserService.java
  src/main/java/com/gitgud/service/recommendation/RecommendationService.java
  src/main/java/com/gitgud/service/util/RealStateUtils.java
  src/main/java/com/gitgud/web/rest/AccountResource.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
  src/main/java/com/gitgud/web/rest/RecommendationController.java
  src/main/webapp/app/@akita/recommended/recommended.model.ts
  src/main/webapp/app/@akita/recommended/recommended.query.ts
  src/main/webapp/app/@akita/recommended/recommended.service.ts
  src/main/webapp/app/@akita/recommended/recommended.store.ts
  src/main/webapp/app/app-routing.module.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/modules/detail/components/images-carrousel/images-carrousel.component.ts
  src/main/webapp/app/modules/detail/components/ips-data/ips-data.component.html
  src/main/webapp/app/modules/detail/components/ips-data/ips-data.component.ts
  src/main/webapp/app/modules/detail/components/recommended/recommended.component.html
  src/main/webapp/app/modules/detail/components/recommended/recommended.component.scss
  src/main/webapp/app/modules/detail/components/recommended/recommended.component.ts
  src/main/webapp/app/modules/detail/components/sidecard-like/sidecard-like.component.ts
  src/main/webapp/app/modules/detail/components/sidecard/sidecard.component.html
  src/main/webapp/app/modules/detail/detail.module.ts
  src/main/webapp/app/modules/detail/detail.route.ts
  src/main/webapp/app/modules/detail/services/can-deactivate.guard.ts
  src/main/webapp/app/modules/detail/services/ips-data.service.ts
  src/main/webapp/app/modules/detail/views/state-detail/state-detail.component.html
  src/main/webapp/app/modules/detail/views/state-detail/state-detail.component.ts
  src/main/webapp/app/shared/real-state-list/real-state-list.component.html
  src/main/webapp/app/shared/real-state-list/real-state-list.component.scss
  src/main/webapp/app/shared/real-state-list/real-state-list.component.ts
  src/main/webapp/app/shared/user-rating/user-rating.component.html
  src/test/java/com/gitgud/web/rest/AccountResourceIntTest.java
Labels: feature

#67 Feature/ratings reviews
  src/main/java/com/gitgud/domain/Review.java
  src/main/java/com/gitgud/domain/User.java
  src/main/java/com/gitgud/service/MailService.java
  src/main/java/com/gitgud/service/RatingsAndReviewsService.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/UserService.java
  src/main/java/com/gitgud/service/dto/UserDTO.java
  src/main/java/com/gitgud/web/rest/AccountResource.java
  src/main/java/com/gitgud/web/rest/RatingsAndReviewsController.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
  src/main/resources/templates/mail/reviewsEmail.html
  src/main/webapp/app/@akita/real-state/real-state.model.ts
  src/main/webapp/app/@akita/real-state/real-state.service.ts
  src/main/webapp/app/@akita/review/review.model.ts
  src/main/webapp/app/@akita/review/review.query.ts
  src/main/webapp/app/@akita/review/review.service.ts
  src/main/webapp/app/@akita/user/user.model.ts
  src/main/webapp/app/@akita/user/user.service.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/modules/detail/components/review-modal/review-modal.component.html
  src/main/webapp/app/modules/detail/components/review-modal/review-modal.component.scss
  src/main/webapp/app/modules/detail/components/review-modal/review-modal.component.ts
  src/main/webapp/app/modules/detail/components/review-modal/review-modal.ts
  src/main/webapp/app/modules/detail/detail.module.ts
  src/main/webapp/app/modules/detail/views/state-detail/state-detail.component.ts
  src/main/webapp/app/modules/view-profile/components/reviews-modal/reviews-modal.component.html
  src/main/webapp/app/modules/view-profile/components/reviews-modal/reviews-modal.component.scss
  src/main/webapp/app/modules/view-profile/components/reviews-modal/reviews-modal.component.ts
  src/main/webapp/app/modules/view-profile/components/user-info/user-info.component.html
  src/main/webapp/app/modules/view-profile/components/user-info/user-info.component.scss
  src/main/webapp/app/modules/view-profile/components/user-info/user-info.component.ts
  src/main/webapp/app/modules/view-profile/utils/modal-type.ts
  src/main/webapp/app/modules/view-profile/view-profile.module.ts
  src/main/webapp/app/modules/view-profile/views/own-profile/own-profile.component.ts
  src/main/webapp/app/shared/angular-material/angular-material.module.ts
  src/main/webapp/app/shared/bought-modal/bought-modal.component.html
  src/main/webapp/app/shared/bought-modal/bought-modal.component.scss
  src/main/webapp/app/shared/bought-modal/bought-modal.component.ts
  src/main/webapp/app/shared/comment/comment.component.html
  src/main/webapp/app/shared/comment/comment.component.scss
  src/main/webapp/app/shared/comment/comment.component.ts
  src/main/webapp/app/shared/listing/listing.component.html
  src/main/webapp/app/shared/real-state-list/real-state-list.component.html
  src/main/webapp/app/shared/real-state-list/real-state-list.component.ts
  src/main/webapp/app/shared/remove-modal/Iremove-modal.ts
  src/main/webapp/app/shared/remove-modal/remove-modal.component.html
  src/main/webapp/app/shared/remove-modal/remove-modal.component.scss
  src/main/webapp/app/shared/remove-modal/remove-modal.component.ts
  src/main/webapp/app/shared/shared.module.ts
  src/main/webapp/app/shared/typeahead/typeahead.component.html
  src/main/webapp/app/shared/typeahead/typeahead.component.scss
  src/main/webapp/app/shared/typeahead/typeahead.component.spec.ts
  src/main/webapp/app/shared/typeahead/typeahead.component.ts
  src/main/webapp/app/shared/user-info/user-info.component.ts
  src/main/webapp/app/shared/user-rating/user-rating.component.html
  src/main/webapp/app/shared/util/remove-type.ts
Labels: feature

#68 Inactivate and restore account, finished
  src/main/java/com/gitgud/config/SecurityConfiguration.java
  src/main/java/com/gitgud/service/UserService.java
  src/main/java/com/gitgud/web/rest/AccountResource.java
Labels: feature

#69 Feature/ratings reviews
  src/main/java/com/gitgud/api/objects/ApiReview.java
  src/main/java/com/gitgud/config/SecurityConfiguration.java
  src/main/java/com/gitgud/repository/RatingsAndReviewsRepository.java
  src/main/java/com/gitgud/service/RatingsAndReviewsService.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/web/rest/RatingsAndReviewsController.java
  src/main/webapp/app/@akita/review/review.service.ts
  src/main/webapp/app/modules/detail/views/state-detail/state-detail.component.ts
  src/main/webapp/app/shared/comment/comment.component.html
Labels: feature

#73 Feature/gitgud reactivate user
  src/main/resources/i18n/messages.properties
  src/main/resources/templates/mail/activationEmail.html
Labels: Improvement

#72 Feature/gitgud recommendations
  src/main/java/com/gitgud/domain/RealState.java
  src/main/java/com/gitgud/repository/UserRepository.java
  src/main/java/com/gitgud/service/RatingsAndReviewsService.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/UserService.java
  src/main/java/com/gitgud/service/recommendation/RecommendationService.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
  src/main/java/com/gitgud/web/rest/util/HeaderUtil.java
  src/main/webapp/app/@akita/external-models/searchFilter.ts
  src/main/webapp/app/@akita/real-state/real-state.model.ts
  src/main/webapp/app/@akita/real-state/real-state.service.ts
  src/main/webapp/app/@akita/recommended/recommended.service.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/layouts/main/main.component.ts
  src/main/webapp/app/layouts/navbar/navbar.component.html
  src/main/webapp/app/modules/detail/components/ips-data/ips-data.component.ts
  src/main/webapp/app/modules/detail/components/sidecard/sidecard.component.html
  src/main/webapp/app/modules/detail/views/state-detail/state-detail.component.ts
  src/main/webapp/app/modules/landing/components/filter-appartment/filter-appartment.component.html
  src/main/webapp/app/modules/landing/components/filter-home/filter-home.component.html
  src/main/webapp/app/modules/landing/components/filter-lot/filter-lot.component.html
  src/main/webapp/app/modules/landing/components/filter-rating/filter-rating.component.html
  src/main/webapp/app/modules/landing/components/filter-rating/filter-rating.component.scss
  src/main/webapp/app/modules/landing/components/filter-rating/filter-rating.component.ts
  src/main/webapp/app/modules/landing/landing.module.ts
  src/main/webapp/app/modules/landing/views/search-results/search-results.component.html
  src/main/webapp/app/modules/landing/views/search-results/search-results.component.ts
  src/main/webapp/app/shared/location-filters/location-filters.component.ts
  src/main/webapp/app/shared/location-filters/location-filters.service.ts
  src/main/webapp/app/shared/meta.service.ts
  src/main/webapp/app/shared/real-state-list/real-state-list.component.html
  src/main/webapp/app/shared/user-rating/user-rating.component.html
  src/main/webapp/app/shared/util/gitgud-lodash/deepCompare.js
  src/main/webapp/index.html
Labels: bug, enhancement, feature

#75 Feature/gitgud reactivate user
  src/main/webapp/app/modules/reactivate-user/views/reactivate-user-view/reactivate-user-view.component.ts
Labels: Improvement, bug
