Repository garyvh2/shozas, pull requests merged in 2019-03, with the labels that each got.

#6 Develop Merge With Api Result Model Generic <T>
  .angulardoc.json
  package-lock.json
  package.json
  src/main/webapp/app/@akita/detail/detail.model.ts
  src/main/webapp/app/@akita/detail/detail.query.ts
  src/main/webapp/app/@akita/detail/detail.service.ts
  src/main/webapp/app/@akita/detail/detail.store.ts
  src/main/webapp/app/@akita/detail/index.ts
  src/main/webapp/app/@akita/detail/sample-data.ts
  src/main/webapp/app/app-routing.module.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/layouts/main/main.component.html
  src/main/webapp/app/modules/detail/components/images-carrousel/images-carrousel.component.html
  src/main/webapp/app/modules/detail/components/images-carrousel/images-carrousel.component.ts
  src/main/webapp/app/modules/detail/detail.module.ts
  src/main/webapp/app/modules/detail/detail.route.ts
  src/main/webapp/app/modules/detail/views/apartment/apartment.component.html
  src/main/webapp/app/modules/detail/views/apartment/apartment.component.ts
  src/main/webapp/app/modules/detail/views/house/house.component.html
  src/main/webapp/app/modules/detail/views/house/house.component.ts
  src/main/webapp/app/modules/detail/views/lot/lot.component.html
  src/main/webapp/app/modules/detail/views/lot/lot.component.ts
  src/main/webapp/app/shared/angular-material/angular-material.module.ts
  src/main/webapp/app/shared/shared-common.module.ts
  src/main/webapp/app/shared/shared-libs.module.ts
  src/main/webapp/app/shared/shared.module.ts
  src/main/webapp/content/scss/_bootstrap-variables.scss
  src/main/webapp/content/scss/vendor.scss
  src/main/webapp/index.html
Labels: enhancement

#10 Feature/gitgud search endpoint
  pom.xml
  src/main/java/com/gitgud/config/MorphiaAutoConfiguration.java
  src/main/java/com/gitgud/domain/ApiResultModel.java
  src/main/java/com/gitgud/domain/ApiSearchParams.java
  src/main/java/com/gitgud/domain/RealState.java
  src/main/java/com/gitgud/domain/User.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/util/CloudinaryUtil.java
  src/main/java/com/gitgud/service/util/ResultType.java
  src/main/java/com/gitgud/web/rest/ApiBaseController.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
Labels: enhancement, good first issue

#14 Feature/gitgud search endpoint
  src/main/java/com/gitgud/api/objects/ApiImage.java
  src/main/java/com/gitgud/api/objects/ApiRealState.java
  src/main/java/com/gitgud/api/objects/ApiResultModel.java
  src/main/java/com/gitgud/api/objects/ApiSearchParams.java
  src/main/java/com/gitgud/api/objects/ApiUser.java
  src/main/java/com/gitgud/domain/User.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/web/rest/ApiBaseController.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
Labels: enhancement

#18 Feature/gitgud search endpoint
  package-lock.json
  src/main/java/com/gitgud/api/objects/ApiRealState.java
  src/main/java/com/gitgud/api/objects/ApiSearchParams.java
  src/main/java/com/gitgud/api/objects/ApiSearchResults.java
  src/main/java/com/gitgud/config/MorphiaAutoConfiguration.java
  src/main/java/com/gitgud/domain/User.java
  src/main/java/com/gitgud/repository/UserRepository.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/UserService.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
Labels: Improvement, enhancement, feature

#19 Adding detail endpoint
  src/main/java/com/gitgud/domain/RealState.java
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
Labels: enhancement, feature

#21 Fixing issue with created day and returning empty if no results
  src/main/java/com/gitgud/domain/RealState.java
  src/main/java/com/gitgud/service/RealStateService.java
Labels: bug

#32 Adding Clodinary and real state defaut images
  pom.xml
  src/main/java/com/gitgud/api/objects/ApiImage.java
  src/main/java/com/gitgud/service/RealStateService.java
Labels: enhancement, feature

#36 fix(service): silence iplocation call when out of request
  src/main/webapp/app/modules/landing/components/location-filters/location-filters.service.ts
  src/main/webapp/app/modules/landing/landing.service.ts
Labels: bug

#37 Feature/crud realstate
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/web/rest/RealStateController.java
Labels: feature

#39 Feature/user management
  src/main/java/com/gitgud/service/RealStateService.java
  src/main/java/com/gitgud/service/UserService.java
  src/main/java/com/gitgud/web/rest/AccountResource.java
Labels: feature

#47 fix(components): default views styles + authorization
  src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html
  src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.scss
  src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.ts
  src/main/webapp/app/account/password-reset/init/password-reset-init.component.html
  src/main/webapp/app/account/password-reset/init/password-reset-init.component.scss
  src/main/webapp/app/account/password-reset/init/password-reset-init.component.ts
  src/main/webapp/app/layouts/error/error.component.html
  src/main/webapp/app/layouts/error/error.component.scss
  src/main/webapp/app/layouts/error/error.component.ts
  src/main/webapp/app/modules/landing/views/search-results/search-results.component.scss
  src/main/webapp/app/modules/listings/listings.route.ts
Labels: bug
